---

- name: create /etc/keystone/keystone.conf file
  template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf owner=root group=root mode=0644

- name: populate the identity service database
  command: su -s /bin/sh -c "keystone-manage db_sync" keystone

- name: initialize fernet keys
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone

- name: remove /var/lib/keystone/keystone.db file
  file: path=/var/lib/keystone/keystone.db state=absent
