---

- name: set memcached configuration for openstack
  copy: src=memcached.conf dest=/etc/memcached.conf owner=root group=root mode=0644

- name: restart memcached
  service: name=memcached state=restarted
