---
# tasks file for compute

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - nova-compute
    - neutron-linuxbridge-agent

- include: chrony_basic_conf.yml

- include: nova_conf.yml

- include: neutron_conf.yml
