---
# tasks file for common

- name: add apt repository for openstack mitaka
  command: add-apt-repository cloud-archive:mitaka

- name: update apt cache
  apt: update_cache=yes

- name: upgrade packages
  apt: upgrade=dist

- name: install packages
  apt: name={{ item }} state=present autoremove=yes
  with_items:
    - chrony
    - python-openstackclient

- name: turns vim default system editor
  alternatives: name=editor path=/usr/bin/vim.basic
